# El archivo application.properties es donde se une el mundo de Docker (infraestructura)
# con el mundo de Spring Boot (código).

spring.application.name=seventeen-management-api


# Conexión a la BD MySQL (Nombre del servicio en Docker: svt-db)
spring.datasource.url=jdbc:mysql://localhost:${DB_PORT_EXTERNAL:3307}/${DB_NAME}
# -> jdbc:mysql://                      : Es el protocolo. Le dice a Java: "usa el conector de MySQL".
# -> localhost:${DB_PORT_EXTERNAL:3307} : A qué dirección mirar. Por defecto el puerto 3307.
# -> /${DB_NAME}                        : Es el nombre de la base de datos.
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# -> Credenciales de la BD usando variables de entorno


# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
# Le dice a Hibernate qué hacer con las tablas
# -> update : Se actualiza automáticamente en MySQL.
# -> create : Borra y crea todo de nuevo cada vez que se inicia.
# -> none   : No hace nada.
spring.jpa.show-sql=true
# Hace que aparezca el código SQL en la consola.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Se confirma a Hibernate el "dialecto" específico de la BD (MySQL 8)


# Seguridad inicial: Spring Security bloquea automáticamente la app.
# Por defecto el usuario es 'user' y uno puede definir la contraseña, sin esta línea
# Spring genera una clave aleatoria cada vez que se inicia.
spring.security.user.password=${APP_PASSWORD}
